version: '2'
services:
      server:
        build: ./
        ports: 
          - 9090:9090
        depends_on:
          - mongodb
        environment:
          WAIT_HOSTS: mongodb:27017

      mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGODB_USER="user" 
          - MONGODB_PASS="pass"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27018:27017
        command: mongod
